site_name: UAC Documentation
site_url: https://github.com/tclahr/uac
nav:
  - 'BASICS':
    - 'Getting started': index.md
  - 'DEFINITIONS':
    - 'Profile file': profile_file.md
    - 'Artifacts file': artifacts_file.md
    - 'Collectors': collectors.md
    - 'Exposed variables': exposed_vars.md
  - 'OUTPUT FILE':
    - 'Output file format': output_file.md
  - 'OTHER':
    - 'Super Timeline creation': super_timeline.md
    - 'Using UAC with CrowdStrike Falcon Real Time Response': using_uac_with_cs_falcon_rtr.md
theme: readthedocs
extra_css: [extra.css]
plugins:
  - search