site_name: UAC Documentation
site_url: https://github.com/tclahr/uac
nav:
  - 'BASICS':
    - 'Getting Started': index.md
  - 'DEFINITIONS':
    - 'Profiles': profiles.md
    - 'Artifacts': artifacts.md
    - 'Exposed Variables': exposed_vars.md
    - 'Exposed Functions': exposed_functions.md
  - 'CONFIG':
    - 'uac.conf': config_file.md
  - 'OUTPUT':
    - 'Output Formats': output_formats.md
  - 'LOG':
    - 'Log Files': log_files.md
  - 'OTHER':
    - 'Parsing UAC output': parsing_uac_output.md
    - 'Using UAC with CrowdStrike Falcon Real Time Response': using_uac_with_cs_falcon_rtr.md
  - 'MISC':
    - 'Testing Lab': testing_lab.md
theme: readthedocs
extra_css: [extra.css]
plugins:
  - search